apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: {{ .Values.wisecow.replicaCount }}
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: "{{ .Values.wisecow.image.repository }}:{{ .Values.wisecow.image.tag }}"
        imagePullPolicy: {{ .Values.wisecow.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.wisecow.port }}
          protocol: TCP