apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # IMPORTANT: Replace with your email
    email: your-email@example.com
    # The production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - http01:
        ingress:
          # This class name must match the one in your Ingress resource
          class: nginx