apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ariefshaik7/wisecow.git'
    path: helm/wisecow-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wisecow 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 