name: CI-CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${{ github.run_id }}

  update-newtag-in-helm:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Update new tag in Helm chart
        run: |
          sed -i "s/tag: .*/tag: '${{ github.run_id }}'/" helm/wisecow-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "ariefshaik001@gmail.com"
          git config --local user.name "ariefshaik7"
          git add helm/wisecow-chart/values.yaml
          git commit -m "Update Helm chart"
          git push    